import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from "@/components/providers/toaster-provider";
import { getServerSession } from "next-auth/next";
import SessionProvider from "@/components/session-provider";
import { authOptions } from "@/lib/auth";
import { nunito, lora } from "@/lib/fonts";
import { ConffettiProvider } from "@/components/providers/confetti-provider";

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${nunito.variable} ${lora.variable} antialiased`}>
        <SessionProvider session={session}>
          <ConffettiProvider />
          <ToastProvider />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
